FROM adoptopenjdk/openjdk11-openj9:jdk-11.0.1.13-alpine-slim

COPY ./target/soallpeach-0.0.1-SNAPSHOT.war /usr/app/

WORKDIR /usr/app

RUN sh -c 'touch soallpeach-0.0.1-SNAPSHOT.war'

ENTRYPOINT ["java","-jar","soallpeach-0.0.1-SNAPSHOT.war","--server.port=80"]